name: CMake Build Fixed

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: renefritze/msvc-dev-cmd@24847ef395cc1f5e04fb9e9f0b3dd1ff1db25675
      - name: Setup CMake
        uses: lukka/get-cmake@latest
        with:
            cmakeVersion: ~3.29.5
            ninjaVersion: ~1.12.1
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake --preset ${{ matrix.os }}
      - name: Build
        run: cmake --build --preset ${{ matrix.os }}