name: CMake Build

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Setup CMake
        uses: lukka/get-cmake@latest
        with:
            cmakeVersion: ~3.29.5
            ninjaVersion: ~1.12.1
      - uses: ilammy/msvc-dev-cmd@v1.13.0
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake --preset ${{ matrix.os }}
      - name: Build
        run: cmake --build --preset ${{ matrix.os }}